<?php

include_once('proud_widgets.features.inc');


/**
 * Implements hook_proud_post_install().
 * These permissions need to be set after the feature has installed.
 */
function proud_widgets_proud_post_install() {
  module_load_include('install', 'proud_widgets', 'proud_widgets');
  proud_widgets_post_install();
}

/**
 * Implements hook_apps_app_info()
 */
function proud_widgets_apps_app_info() {
  return array(
    'configure form' => 'proud_widgets_configure_form',
  );
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function proud_widgets_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/** 
 * Implementation of hook_entity_info_alter()
 */
function proud_widgets_entity_info_alter(&$entity_info) {
  
  // Basic file
  /*$entity_info['fieldable_panels_pane']['bundles']['basic_file'] = array(
    'label' => t('file'),
    'description' => t('file'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'proud_widgets') . '/images/icon_file.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/basic-file',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );*/

  // Basic Image
  $entity_info['fieldable_panels_pane']['bundles']['media'] = array(
    'label' => t('Media'),
    'description' => t('Media'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'proud_widgets') . '/images/icon_image.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/media',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

  // Basic text
  $entity_info['fieldable_panels_pane']['bundles']['text'] = array(
    'label' => t('Text'),
    'description' => t('Text'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'proud_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/text',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

  // Quick links
  /*$entity_info['fieldable_panels_pane']['bundles']['quick_links'] = array(
    'label' => t('Links'),
    'description' => t('Links'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'proud_widgets') . '/images/icon_link.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/quick-links',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );*/

  $entity_info['fieldable_panels_pane']['bundles']['icon_button'] = array(
    'label' => t('Icon button'),
    'description' => t('Icon button for quick links'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'proud_widgets') . '/images/icon_link.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/icon-button',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
  // Basic video
  /*$entity_info['fieldable_panels_pane']['bundles']['video'] = array(
    'label' => t('video'),
    'description' => t('video'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'proud_widgets') . '/images/icon_video.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/video',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );*/
}