<?php
/**
 * @file
 * Code for the Proud Admin feature.
 */

include_once 'proud_admin.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function proud_admin_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_admin_paths_alter()
 **/
function proud_admin_admin_paths_alter(&$paths) {
  $paths['user'] = TRUE;
  $paths['user/*'] = TRUE;
  return $paths;
}


/**
 * Implements hook_theme().
 */
function proud_admin_theme() {
  //$path = drupal_get_path('module', 'proud_admin');
  global $base_url;
  return array(
    'proud_admin_add_content' => array(
      'template' => 'templates/add-content',
      'variables' => array(
        'dropdown' => '',
      )
    ),
    'proud_admin_add_content_dropdown' => array(
      'template' => 'templates/add-content-dropdown',
      'variables' => array(
        'types' => proud_admin_node_types(),
      )
    ),
    'proud_admin_button' => array(
      'template' => 'templates/button',
      'variables' => array(
        'link' => FALSE,
        'icon' => '',
        'markup' => '',
      )
    ),

    
  );
}




function proud_admin_node_type_metadata() {
  return array(
    'page' => array(
      'icon' => 'file',
      'color' => 'rgb(188, 133, 230)',
    ),
    'article' => array(
      'icon' => 'newspaper-o',
      'color' => '#8AB734',
    ),
    'landingpage' => array(
      'icon' => 'th-list',
      'color' => 'rgb(77, 195, 255)',
    ),
    'event' => array(
      'icon' => 'calendar',
      'color' => 'rgb(223, 123, 170)',
    ),
    'link' => array(
      'icon' => 'link',
      'color' => 'rgb(246, 141, 56)',
    ),
    'document' => array(
      'icon' => 'upload',
      'color' => 'rgb(178, 118, 54)',
    ),
    'gdrive' => array(
      'icon' => 'cloud-download',
      'color' => 'rgb(178, 118, 54)',
    ),
    
  );
}


function proud_admin_extra_colors() {
  return array(
    '#14A88E',
    '#DF7BAA',
    '#A4506C',
    '#BC85E6',
  );
}

/**
 * Callback to JSON endpoint to return node types.
 */
function proud_admin_node_types() {
  $return = node_type_get_types();
  $metas = proud_admin_node_type_metadata();
  $colors = proud_admin_extra_colors();
  foreach ($return as &$type) {
    if (!empty($metas[$type->type])) {
      $meta = $metas[$type->type];
      $type->icon = $meta['icon'];
      $type->color = $meta['color'];
    }
    else {
      $type->icon = 'file';
      $type->color = $colors[array_rand($colors)];
    }    
  }
  return $return;
}

