<?php

/**
 * @file
 * Administration proud_toolbar for quick access to top level administration items.
 */


/**
 * Implements hook_permission().
 */
function proud_toolbar_permission() {
  return array(
    'access proud toolbar' => array(
      'title' => t('Use the Proud Toolbar'),
      'description' => t('Use the Proud Toolbar unless admin_menu is available'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function proud_toolbar_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'proud_toolbar');
  $items['proud_toolbar'] = array(
    'render element' => 'toolbar',
    'template' => 'proud-toolbar',
    'path' => $path,
  );
  $items['proud_sidebar'] = array(
    'render element' => 'sidebar',
    'template' => 'proud-sidebar',
    'path' => $path,
  );
  $items['proud_navbar'] = array(
    'render element' => 'nav',
    'template' => 'proud-navbar',
    'path' => $path
  );
  $items['proud_navbar_overlay'] = array(
    'render element' => 'overlay',
    'template' => 'proud-navbar-overlay',
    'path' => $path
  );
  return $items;
}

/**
 * Implements hook_menu().
 */
//function proud_toolbar_menu() {
  /*$items['proud_toolbar/toggle'] = array(
    'title' => 'Toggle drawer visibility',
    'type' => MENU_CALLBACK,
    'page callback' => 'proud_toolbar_toggle_page',
    'access arguments' => array('access proud toolbar'),
  );*/
  //return $items;
//}

/**
 * Implements hook_page_build().
 *
 * Add admin proud_toolbar to the page_top region automatically.
 */
function proud_toolbar_page_build(&$page) {
  if (!(module_exists('admin_menu') && user_access('access administration menu'))) {
    module_load_include('inc', 'proud_toolbar', 'includes/toolbar');
    $page['page_top']['proud_toolbar'] = array(
      '#pre_render' => array('proud_toolbar_pre_render_toolbar'),
      '#access' => user_access('access proud toolbar'),
    );
  }
  if (proud_toolbar_sidebar_visible(current_path())) {
    module_load_include('inc', 'proud_toolbar', 'includes/sidebar');
    $page['page_top']['proud_sidebar'] = array(
      '#pre_render' => array('proud_toolbar_pre_render_sidebar'),
      '#access' => user_access('access proud toolbar'),
    );
  }
  if (!path_is_admin(current_path())) {
    module_load_include('inc', 'proud_toolbar', 'includes/navbar');
    $page['page_top']['proud_navbar'] = array(
      '#pre_render' => array('proud_toolbar_pre_render_navbar'),
      '#access' => true
    );
    $page['page_bottom']['proud_navbar_overlay'] = array(
      '#pre_render' => array('proud_toolbar_pre_render_navbar_overlay'),
      '#access' => true
    );
  }
}


/**
 * Implements hook_preprocess_html().
 *
 * Add some page classes, so global page theming can adjust to the proud_toolbar.
 */
function proud_toolbar_preprocess_html(&$vars) {
  if (isset($vars['page']['page_top']['proud_toolbar']) && user_access('access proud toolbar')) {
    $vars['classes_array'][] = 'proud-toolbar-active';
  }
  if (isset($vars['page']['page_top']['proud_sidebar']) && user_access('access proud toolbar')) {
    $vars['classes_array'][] = 'proud-sidebar-active';
  }
  if (isset($vars['page']['page_top']['proud_navbar'])) {
    $vars['classes_array'][] = 'proud-navbar-active';
  }
}



/**
 * Implements hook_system_info_alter().
 *
 * Indicate that the 'page_top' region (in which the proud_toolbar will be displayed)
 * is an overlay supplemental region that should be refreshed whenever its
 * content is updated.
 *
 * This information is provided for any module that might need to use it, not
 * just the core Overlay module.
 */
function proud_toolbar_system_info_alter(&$info, $file, $type) {
  if ($type == 'theme') {
    $info['overlay_supplemental_regions'][] = 'page_top';
  }
}


/**
 * Returns true if sidebar should be rendered
 */
function proud_toolbar_sidebar_visible($path) {
  $path = current_path();
  if(!path_is_admin($path)) {
    return false;
  }
  // Paths to exclude
  $exlude_paths = array(
    'node\/add',
    'node\/.*?\/edit',
    'admin\/modules',
    'admin\/people\/permissions'
  );
  // Alter
  drupal_alter('proud_toolbar_sidebar_visible', $exlude_paths);
  foreach ($exlude_paths as $excluded) {
    if(preg_match('/'.$excluded.'/', $path)) {
      return false;
    }
  }
  return true;
} 