<?php
// Plugin definition
$plugin = array(
  'title' => t('Landing page'),
  'icon' => 'landing.png',
  'category' => t('Proud'),
  'theme' => 'proud_landing',
  'regions' => array(
    'banner' => t('Banner (full-width)'),
    'sidebar' => t('Sidebar'),
    'top' => t('Top content'),
    'divider1' => t('Divider 1'),
    'divider2' => t('Divider 2'),
    'tri1' => t('Three-col 1'),
    'tri2' => t('Three-col 2'),
    'tri3' => t('Three-col 3'),
    'divider3' => t('Divider 3'),
    'col1' => t('Two-col 1'),
    'col2' => t('Two-col 2'),
    'divider4' => t('Divider 4'),
    'bottom' => t('Content bottom'),
    'footer' => t('Footer (full-width)'),
  ),
);
