<?php
/**
 * @file
 * Install file.
 */

/**
 * Implements hook_install().
 */
function proud_event_display_install() {
  $type = 'event';
  if (module_exists('proud_core')) {
    module_load_include('inc', 'proud_core', 'includes/proud_core.permissions');
    $permissions = proud_core_panelizer_permissions('page', "proud_$type_display");
    proud_core_add_permissions($permissions);
  }
}


/*
 * Implements hook_uninstall().
 */
function proud_event_display_uninstall() {
}